name: Continuous Build

on:
  push:
    # This runs the job on every push to any branch
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # Fetch all history to ensure GoReleaser can calculate version info
          fetch-depth: 0

      - name: Set up Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: "1.25" # Set your preferred Go version

      - name: Ensure GoReleaser is installed
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> v2'
          install-only: true

      - name: Run Makefile target
        run: make 
        env:
          # GITHUB_TOKEN is still required for certain features, but
          # no release will be created with '--snapshot'.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
